spin_version = "1"
authors = ["Matt Butcher <matt.butcher@fermyon.com>"]
description = "An HTTP equivalent to UNIX Finger"
name = "finger"
trigger = { type = "http", base = "/" }
version = "7.0.0"

[[component]]
id = "finger"
source = "target/wasm32-wasi/release/finger.wasm"
files = ["files/*", "files/templates/*"]
allowed_http_hosts = ["finger-f6ooog56.fermyon.app"]
# environment = {"REDIS_HOST" = "ENTER YOUR HOST AND UNCOMMENT"}
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"

[[component]]
# source = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.1/spin_static_fs.wasm"
source = "modules/spin_static_fs.wasm"
id = "fileserver"
files = [{ source = "static/", destination = "/" }, ]
[component.trigger]
route = "/static/..."
